version: '{build}'  
os: Visual Studio 2017
pull_requests:  
  do_not_increment_build_number: true
branches:  
  only:
  - master
nuget:  
  disable_publish_on_pr: true
build_script:  
- ps: .\Build.ps1
test: off  
artifacts:
- path: .\**\artifacts\**\Serilog.*.nupkg
  name: NuGet
deploy:
- provider: NuGet
  name: production
  api_key:
    secure: V+SBtVPL19ba6Vsdq3YpFFNs2hDcVU7hVSzk1+ncdyUDvx7WsdzNLmRMN5QRYySi
  on:
    branch: master
    appveyor_repo_tag: true